sonar.projectKey=minor-project-react-app
sonar.projectName=Minor Project React App
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/build/**,**/*.test.js
sonar.tests=src
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
